### PR TITLE
setting up db schema through repl

### PR DESCRIPTION
**Pull request by elisehuard**

### CODE REVIEW

**Comment by acron0** [comment]
This installation guide doesn't assume understanding of REPLs or schemas. Any chance we could provide a command line script, such as:

``` bash
#!/usr/bin/env bash
(printf "
(require '[db-setup :refer [load-db-schema!]])
(require '[witan.app.config :as c])
(load-db-schema! c/config)
(exit)\r\n"; cat <&0) | lein repl
```

And then simply replace the `cqlsh -f cql/dev-schema.cql` with calling the script?

**Comment by acron0** [comment]
I should qualify, there is some REPL instructions in this guide but they're much more hand-holding than this.

**Comment by acron0** [comment]
Perfect, thanks :shipit:

**Comment by elisehuard** [comment]
actually could be an easy shortcut for us as well

**Comment by acron0** [comment]
Definitely for me because I'm super lazy

**Pull request merged**
